name: Process Cops Australia

on:
  schedule:
    - cron: '*/10 * * * *' # UTC
  workflow_dispatch:

concurrency:
  group: waze-data
  cancel-in-progress: false

jobs:
  collect-and-convert:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Checkout data branch to temp directory
        uses: actions/checkout@v4
        with:
          ref: data
          path: temp_data

      - name: Bring forward settled tile state (if exists)
        run: |
          if [ -f temp_data/australia_settled_tiles.json ]; then
            cp temp_data/australia_settled_tiles.json australia_settled_tiles.json
          else
            echo "No australia_settled_tiles.json found from previous run."
          fi

      - name: Collect Waze alerts
        run: |
            python waze_json.py \
            --region australia \
            --out-name australia_alerts.json \
            --state-path australia_settled_tiles.json \
            --out-dir ./

      - name: Convert to police GeoJSON
        run: |
          if [ -f australia_alerts.json ]; then
            python waze_police_geojson.py australia_alerts.json australia_police.geojson
          else
            echo "australia_alerts.json not found, skipping conversion"; exit 1
          fi

      - name: Configure Git for data branch (in temp_data repo)
        working-directory: temp_data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push to data branch
        working-directory: temp_data
        run: |
          # Copy artifacts into the data branch working tree if they exist
          [ -f ../australia_alerts.json ] && cp ../australia_alerts.json . || true
          [ -f ../australia_police.geojson ] && cp ../australia_police.geojson . || true
          [ -f ../australia_settled_tiles.json ] && cp ../australia_settled_tiles.json . || true

          git add australia_alerts.json australia_police.geojson australia_settled_tiles.json || true
          timestamp=$(date -u "+%Y-%m-%d %H:%M:%S UTC")
          git commit -m "Update Waze data - $timestamp" || echo "No changes to commit"
          git push origin data
