name: Collect Waze Data

on:
  schedule:
    - cron: '*/10 * * * *' # UTC
  workflow_dispatch:

concurrency:
  group: waze-data
  cancel-in-progress: false

jobs:
  collect-and-convert:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          # cache-dependency-path: requirements.txt  # if you add one

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Checkout data branch to temp directory
        uses: actions/checkout@v4
        with:
          ref: data
          path: temp_data

      - name: Bring forward settled tile state (if exists)
        run: |
          if [ -f temp_data/settled_tiles.json ]; then
            cp temp_data/settled_tiles.json settled_tiles.json
          else
            echo "No settled_tiles.json found from previous run."
          fi

      - name: Collect Waze alerts
        run: |
          # Ensure the output name here MATCHES what your extractor writes.
          # If your extractor produces timestamped files, either:
          #   1) pass a flag to force sydney_alerts.json, or
          #   2) capture the generated name programmatically.
          python waze_grid.py --region sydney --out-name sydney_alerts.json

      - name: Convert to police GeoJSON
        run: |
          if [ -f sydney_alerts.json ]; then
            python waze_police_geojson.py sydney_alerts.json sydney_police.geojson
          else
            echo "sydney_alerts.json not found, skipping conversion"; exit 1
          fi

      - name: Configure Git for data branch (in temp_data repo)
        working-directory: temp_data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push to data branch
        working-directory: temp_data
        run: |
          # Copy artifacts into the data branch working tree if they exist
          [ -f ../sydney_alerts.json ] && cp ../sydney_alerts.json . || true
          [ -f ../sydney_police.geojson ] && cp ../sydney_police.geojson . || true
          [ -f ../settled_tiles.json ] && cp ../settled_tiles.json . || true

          git add sydney_alerts.json sydney_police.geojson settled_tiles.json || true
          timestamp=$(date -u "+%Y-%m-%d %H:%M:%S UTC")
          git commit -m "Update Waze data - $timestamp" || echo "No changes to commit"
          git push origin data
